apiVersion: v1
kind: ReplicationController
metadata:
  name: go-cfgwatch
spec:
  template:
    metadata:
      labels:
        app: go-cfgwatch
    spec:
      containers:
        - name:  go-cfgwatch
          image: r00tsh3ll/go-cfgwatch
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: go-configmap
